quarkus:
  http:
    port: 8080
  container-image:
    group: ""
    name: ms-frecuencias-nombre
    tag: latest
    registry: franciscoct
  kubernetes:
    namespace: app-datos
  log:
    level: INFO
    file:
      enable: true
      path: ./log/ms-frecuencias-nombre.log
      level: INFO
      format: '{"log_data":{"fecha":"%d{yyyy-MM-dd HH:mm:ss}","Level":"%-5p","Mensaje":"%m","servicios":[%X{servicios}],"TiempoTotal":%X{tiempo}}}%n'
      rotation:
        max-file-size: 200M
        max-backup-index: 5
        rotate-on-boot: true
        file-suffix: .yyyy-MM-dd
  smallrye-openapi:
    path: /contrato-interfaz-ms-frecuencias-nombre
    info-title: Contrato de interfaz Microservicio de Frecuencias.
    info-version: 1.0.0
    #info-descripcion: Contrato de interfaz para la consulta de frecuencia de nombres propios.
frecuencias:
  conexionesdb:
    c3remesas:
      credenciales:
        usuario: HcJMnM8gN-TKHnpBpbWb3A
        contrasena: uQ9Rvb5ntqzOEFmBEjGoUQ
      ip: yv2LD6xR80tmRP8w85txug
      port: CToWpkbX-HoHYUG1vmdmfQ
      name: lI0O4KmZ5PKfmkBf-hLKjg
      esquema: zhr_8DwfomUUehvAapsnQQ
      paquete: C1V_vwz-4tDrxvaz_MkUHA
      sp: S0GfqrYKn5SMIq8lIty8cA